name: Rancher network healthcheck
description: |
  Rancher network healthcheck
version: v0.0.1
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
