version: '2'
services:
  network-healthcheck:
    image: niusmallnan/network-healthcheck:v0.1.0
    labels:
      io.rancher.scheduler.global: 'true'
    environment:
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
      RANCHER_METADATA_IP: '${RANCHER_METADATA_IP}'
      ROUTER_HTTP_CHECK: '${ROUTER_HTTP_CHECK}'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
